language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

cache:
    - apt
    - pip

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y liblo7
    - sudo apt-get install -y liblo-dev

# command to install dependencies
install:
    - pip install Cython
    - pip install -r requirements.travis.txt
    - pip install .

# command to run tests
script: py.test
